-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 15:51:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moedaEstudantil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moedaEstudantil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moedaEstudantil` DEFAULT CHARACTER SET utf8 ;
USE `moedaEstudantil` ;

-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Curso` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `endereco` VARCHAR(500) NULL,
  `moeda` INT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Curso_idCurso`, `Instituicao_id`),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Aluno_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `moedaEstudantil`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `moedaEstudantil`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Vantagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Vantagens` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Vantagens` (
  `idVantagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `foto` VARCHAR(45) NULL,
  `aluno_has_vantagens_idAluno` INT NOT NULL,
  `aluno_has_vantagens_Aluno_idAluno` VARCHAR(45) NOT NULL,
  `aluno_has_vantagens_Aluno_Curso_idCurso` INT NOT NULL,
  `Empresa_id` INT NOT NULL,
  PRIMARY KEY (`idVantagem`, `aluno_has_vantagens_idAluno`, `aluno_has_vantagens_Aluno_idAluno`, `aluno_has_vantagens_Aluno_Curso_idCurso`, `Empresa_id`),
  INDEX `fk_Vantagens_Empresa1_idx` (`Empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vantagens_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `moedaEstudantil`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Professor` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(500) NOT NULL,
  `moeda` INT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Instituicao_id`),
  INDEX `fk_Professor_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `moedaEstudantil`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Transacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Transacoes` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`id`, `Aluno_idAluno`, `Professor_idProfessor`),
  INDEX `fk_Transacoes_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Transacoes_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Transacoes_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacoes_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Vantagens_has_Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Vantagens_has_Aluno` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Vantagens_has_Aluno` (
  `Vantagens_idVantagem` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`Vantagens_idVantagem`, `Aluno_idAluno`),
  INDEX `fk_Vantagens_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Vantagens_has_Aluno_Vantagens1_idx` (`Vantagens_idVantagem` ASC) VISIBLE,
  CONSTRAINT `fk_Vantagens_has_Aluno_Vantagens1`
    FOREIGN KEY (`Vantagens_idVantagem`)
    REFERENCES `moedaEstudantil`.`Vantagens` (`idVantagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vantagens_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `moedaEstudantil`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT into instituicao values (NULL, "puc");
insert into curso values (NULL, "curso1");
