-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 15:51:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moedaEstudantil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moedaEstudantil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moedaEstudantil` DEFAULT CHARACTER SET utf8 ;
USE `moedaEstudantil` ;

-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Curso` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `endereco` VARCHAR(500) NULL,
  `moeda` INT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Curso_idCurso`, `Instituicao_id`),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Aluno_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `moedaEstudantil`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `moedaEstudantil`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Vantagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Vantagens` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Vantagens` (
  `idVantagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `foto` TEXT NULL,
  `Empresa_id` INT NOT NULL,
  `Preco` FLOAT NOT NULL,
  PRIMARY KEY (`idVantagem`, `Empresa_id`),
  INDEX `fk_Vantagens_Empresa1_idx` (`Empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vantagens_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `moedaEstudantil`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Professor` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(500) NOT NULL,
  `moeda` INT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Instituicao_id`),
  INDEX `fk_Professor_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `moedaEstudantil`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Transacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Transacoes` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`id`, `Aluno_idAluno`, `Professor_idProfessor`),
  INDEX `fk_Transacoes_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Transacoes_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Transacoes_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `moedaestudantil`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacoes_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `moedaestudantil`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moedaEstudantil`.`Vantagens_has_Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moedaEstudantil`.`Vantagens_has_Aluno` ;

CREATE TABLE IF NOT EXISTS `moedaEstudantil`.`Vantagens_has_Aluno` (
  `Vantagens_idVantagem` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`Vantagens_idVantagem`, `Aluno_idAluno`),
  INDEX `fk_Vantagens_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Vantagens_has_Aluno_Vantagens1_idx` (`Vantagens_idVantagem` ASC) VISIBLE,
  CONSTRAINT `fk_Vantagens_has_Aluno_Vantagens1`
    FOREIGN KEY (`Vantagens_idVantagem`)
    REFERENCES `moedaEstudantil`.`Vantagens` (`idVantagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vantagens_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `moedaEstudantil`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT into instituicao values (NULL, "puc");
INSERT INTO `moedaestudantil`.`instituicao` (`nome`) VALUES ('santa maria');

-- insert into Professor values (NULL, "josé", "11111111111", "j@gmail.com", "123", "1123", "rua l", NULL, 1);
-- Insert Professors
INSERT INTO `moedaEstudantil`.`Professor` (`nome`, `cpf`, `email`, `senha`, `rg`, `endereco`, `moeda`, `Instituicao_id`) VALUES ('Professor1', '111.111.111-11', 'professor1@email.com', 'senha1', '11.111.111-1', 'Endereco 1', 100, 1);
INSERT INTO `moedaEstudantil`.`Professor` (`nome`, `cpf`, `email`, `senha`, `rg`, `endereco`, `moeda`, `Instituicao_id`) VALUES ('Professor2', '222.222.222-22', 'professor2@email.com', 'senha2', '22.222.222-2', 'Endereco 2', 200, 1);
INSERT INTO `moedaEstudantil`.`Professor` (`nome`, `cpf`, `email`, `senha`, `rg`, `endereco`, `moeda`, `Instituicao_id`) VALUES ('Professor3', '333.333.333-33', 'professor3@email.com', 'senha3', '33.333.333-3', 'Endereco 3', 300, 1);
INSERT INTO `moedaEstudantil`.`Professor` (`nome`, `cpf`, `email`, `senha`, `rg`, `endereco`, `moeda`, `Instituicao_id`) VALUES ('Professor4', '444.444.444-44', 'professor4@email.com', 'senha4', '44.444.444-4', 'Endereco 4', 400, 1);
INSERT INTO `moedaEstudantil`.`Professor` (`nome`, `cpf`, `email`, `senha`, `rg`, `endereco`, `moeda`, `Instituicao_id`) VALUES ('Professor5', '555.555.555-55', 'professor5@email.com', 'senha5', '55.555.555-5', 'Endereco 5', 500, 1);

-- Insert Alunos
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno1','senha1','aluno1@email.com','111.111.111-11','11.111.111-1','Endereco 1',100,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno2','senha2','aluno2@email.com','222.222.222-22','22.222.222-2','Endereco 2',200,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno3','senha3','aluno3@email.com','333.333.333-33','33.333.333-3','Endereco 3',300,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno4','senha4','aluno4@email.com','444.444.444-44','44.444.444-4','Endereco 4',400,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno5','senha5','aluno5@email.com','555.555.555-55','55.555.555-5','Endereco 5',500,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno6','senha6','aluno6@email.com','666.666.666-66','66.666.666-6','Endereco 6',600,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno7','senha7','aluno7@email.com','777.777.777-77','77.777.777-7','Endereco 7',700,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno8','senha8','aluno8@email.com','888.888.888-88','88.888.888-8','Endereco 8',800,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno9','senha9','aluno9@email.com','999.999.999-99','99.999.999-9','Endereco 9',900,1,1);
INSERT INTO `moedaEstudantil`.`Aluno` (`nome`,`senha`,`email`,`cpf`,`rg`,`endereco`,`moeda`,`Curso_idCurso`,`Instituicao_id`) VALUES ('Aluno10', 'senha10', 'aluno10@email.com', '1010101010-10', '10.10101010-10', 'Endereco 10', 1000, 1, 1);

INSERT INTO empresa (`nome`, `cnpj`, `email`, `senha`) VALUES ('Sony', '00000000000000', 'sony@gmail.com', '123');
INSERT INTO empresa (`nome`, `cnpj`, `email`, `senha`) VALUES ('Acttus', '99999999999999', 'acttus@gmail.com', '123');

INSERT INTO `moedaestudantil`.`curso` (`nome`) VALUES ('Eng. Software');
INSERT INTO `moedaestudantil`.`curso` (`nome`) VALUES ('Jogos Digitais');
-- Insert Transacoes
INSERT INTO moedaEstudantil.Transacoes (valor, descricao, Aluno_idAluno, Professor_idProfessor) VALUES (10, "Transacao 1", 1, 1);
INSERT INTO moedaEstudantil.Transacoes (valor, descricao, Aluno_idAluno, Professor_idProfessor) VALUES (20, "Transacao 2", 2, 2);
INSERT INTO moedaEstudantil.Transacoes (valor, descricao, Aluno_idAluno, Professor_idProfessor) VALUES (30, "Transacao 3", 3, 3);
INSERT INTO moedaEstudantil.Transacoes (valor, descricao, Aluno_idAluno, Professor_idProfessor) VALUES (40, "Transacao 4", 4, 4);
INSERT INTO moedaEstudantil.Transacoes (valor, descricao, Aluno_idAluno, Professor_idProfessor) VALUES (50, "Transacao 5", 5, 5);

INSERT INTO `moedaestudantil`.`vantagens` (`nome`, `descricao`, `foto`, `Empresa_id`, `Preco`) VALUES ('10 créditos', 'Créditos equivalentes a 10 reais para sua carteira digital na loja da Sony', 'https://carrefourbr.vtexassets.com/arquivos/ids/63812139/playstore-10.png?v=637929105618030000empresa', '1', '5');
INSERT INTO `moedaestudantil`.`vantagens` (`nome`, `descricao`, `foto`, `Empresa_id`, `Preco`) VALUES ('Vale presente 20 reais', '20 reais de desconto em qualquer compra de produtos Acttus', 'https://www.acttuscosmeticos.com.br/wp-content/uploads/2016/11/Matizee-Acttus.png', '2', '10');
INSERT INTO `moedaestudantil`.`vantagens` (`nome`, `descricao`, `foto`, `Empresa_id`, `Preco`) VALUES ('Amostra gratis', 'Vale amostra de 50ml de produtos capilares', 'https://i1.wp.com/www.acttuscosmeticos.com.br/wp-content/uploads/2016/12/Ampolas-instantaneas-Power-repair-acttus-cosmetico.jpg?fit=1068%2C712&ssl=1', '2', '15');
INSERT INTO `moedaestudantil`.`vantagens` (`nome`, `descricao`, `foto`, `Empresa_id`, `Preco`) VALUES ('25 créditos', 'Créditos equivalentes a 25 reais para sua carteira digital na loja da Sony', 'https://m.media-amazon.com/images/I/61+ggd56S4L._AC_UF1000,1000_QL80_.jpg', '1', '10');
INSERT INTO `moedaestudantil`.`vantagens` (`nome`, `descricao`, `foto`, `Empresa_id`, `Preco`) VALUES ('50 créditos', 'Créditos equivalentes a 50 reais para sua carteira digital na loja da Sony', 'https://shop.post.ch/medias/sys_master/images/images/h39/h18/9123258892318/product-755116-mainpicture-Default-WorkingFormat-380Wx380H.jpg', '1', '20');

INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('4', '1');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('1', '2');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('2', '2');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('5', '3');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('3', '4');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('5', '4');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('2', '5');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('3', '5');
INSERT INTO `moedaestudantil`.`vantagens_has_aluno` (`Vantagens_idVantagem`, `Aluno_idAluno`) VALUES ('5', '5');